package com.uhc.workouttracker.core.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.migration.Migration
import androidx.sqlite.SQLiteConnection
import com.uhc.workouttracker.core.db.dao.ExerciseDao
import com.uhc.workouttracker.core.db.dao.MuscleGroupDao
import com.uhc.workouttracker.core.db.entity.ExerciseEntity
import com.uhc.workouttracker.core.db.entity.MuscleGroupEntity
import com.uhc.workouttracker.core.db.entity.WeightLogEntity

@Database(
    entities = [MuscleGroupEntity::class, ExerciseEntity::class, WeightLogEntity::class],
    version = 2,
    exportSchema = true
)
@ConstructedBy(WorkoutTrackerDatabaseConstructor::class)
abstract class WorkoutTrackerDatabase : RoomDatabase() {
    abstract fun muscleGroupDao(): MuscleGroupDao
    abstract fun exerciseDao(): ExerciseDao

    companion object {
        val MIGRATION_1_2 = object : Migration(1, 2) {
            override fun migrate(connection: SQLiteConnection) {
                connection.prepare("ALTER TABLE weight_logs ADD COLUMN date TEXT NOT NULL DEFAULT ''").use {
                    it.step()
                }
            }
        }
    }
}

// expect declared here; actual is generated by KSP for each target
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object WorkoutTrackerDatabaseConstructor : RoomDatabaseConstructor<WorkoutTrackerDatabase>
